%YAML:1.0
methodName: "StereoBM"
preFilterSize: 131
preFilterCap: 61
SADWindowSize: 67
minDisparity: 0
numberOfDisparities: 16
textureThreshold: 9600
uniquenessRatio: 15
speckleWindowSize: 0
speckleRange: 0
disp12MaxDiff: 1
