%YAML:1.0
Q: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 1., 0., 0., -2.943488998413086e+02, 0., 1., 0.,
       -2.2747732162475586e+02, 0., 0., 0., 7.520932983335229e+02, 0.,
       0., 3.8293922455331292e-01, 0. ]
